all: files compile
	

compile:
	gcc ./SOSynch.c -o SOSynch

run:
	./SOSynch ~/Desktop/proj1 ~/Desktop/proj2 -r -t 300 -s 400

files:
	bash test

files1:
	mkdir ~/Desktop/proj1
	cd ~/Desktop/proj1
	touch ~/Desktop/proj1/1
	echo bruh > ~/Desktop/proj1/1
	touch ~/Desktop/proj1/2
	touch ~/Desktop/proj1/3
	touch ~/Desktop/proj1/5
	touch ~/Desktop/proj1/6
	touch ~/Desktop/proj1/7
	touch ~/Desktop/proj1/8
	mkdir ~/Desktop/proj1/4
	touch ~/Desktop/proj1/4/1
	touch ~/Desktop/proj1/4/2
	touch ~/Desktop/proj1/4/3



files2:
	mkdir ~/Desktop/proj2
	touch ~/Desktop/proj2/1
	touch ~/Desktop/proj2/2
	touch ~/Desktop/proj2/3
	touch ~/Desktop/proj2/44
	touch ~/Desktop/proj2/51
	touch ~/Desktop/proj2/67
	mkdir ~/Desktop/proj2/22
	mkdir ~/Desktop/proj2/99
	touch ~/Desktop/proj2/22/aaaaa
	touch ~/Desktop/proj2/22/1
	touch ~/Desktop/proj2/22/2
	touch ~/Desktop/proj2/22/3
	touch ~/Desktop/proj2/99/1
	touch ~/Desktop/proj2/99/2
	touch ~/Desktop/proj2/99/3
	touch ~/Desktop/proj2/99/44
	touch ~/Desktop/proj2/99/51
	touch ~/Desktop/proj2/99/67

clean:
	rm -r ~/Desktop/proj1
	rm -r ~/Desktop/proj2

